server:
  port: 8080

jwt:
  secret: "a3f8d7e0b2c491a6f5289e3b762c8d4f1e9a6b5c4d3e2f1a0b9c8d7e6f5a4b3"
  expiration: 86400000  # Token 过期时间（24小时）

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      # 连接池基本配置
      pool-name: IM-HikariPool
      minimum-idle: 5              # 最小空闲连接数 (默认与maximum-pool-size相同)
      maximum-pool-size: 20        # 最大连接数 (推荐值: (core_count * 2) + effective_spindle_count)
      idle-timeout: 600000         # 空闲连接超时时间(ms)，默认600000(10分钟)
      max-lifetime: 1800000        # 连接最大存活时间(ms)，默认1800000(30分钟)
      connection-timeout: 30000    # 连接超时时间(ms)，默认30000(30秒)
      initialization-fail-timeout: 1 # 初始化失败超时(秒)，默认1

      # 连接测试配置
      connection-test-query: SELECT 1  # MySQL不需要，有JDBC4的isValid()
      validation-timeout: 5000      # 验证超时(ms)

      # 性能优化配置
      leak-detection-threshold: 60000 # 连接泄漏检测阈值(ms)，0表示禁用
      allow-pool-suspension: false  # 是否允许暂停连接池
      read-only: false             # 是否只读连接池
      register-mbeans: false       # 是否注册JMX MBeans

      # 连接属性
      data-source-properties:
        cachePrepStmts: true       # 启用预编译语句缓存
        prepStmtCacheSize: 250     # 预编译缓存大小
        prepStmtCacheSqlLimit: 2048 # 预编译SQL长度限制
        useServerPrepStmts: true   # 使用服务端预编译
        useLocalSessionState: true # 使用本地会话状态
        rewriteBatchedStatements: true # 优化批量操作
        cacheResultSetMetadata: true # 缓存结果集元数据
        cacheServerConfiguration: true # 缓存服务端配置
        elideSetAutoCommits: true  # 优化autoCommit设置
        maintainTimeStats: false    # 关闭耗时统计(提升性能)
  redis:
    host: localhost
    port: 6379
    password:  # 如果有密码，请设置
    database: 0
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数
        max-idle: 20    # 连接池中的最大空闲连接
        min-idle: 5     # 连接池中的最小空闲连接
        max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 500       # 连接超时时间（毫秒）

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
  global-config:
    db-config:
      id-type: auto # 主键自增
    banner: off

# 日志配置
logging:
  level:
    com.naz1k1: info
    org.springframework: warn

netty:
  websocket:
    port: 8888
    path: /ws
  boss:
    thread:
      count: 1
  worker:
    thread:
      count: 4