server:
  port: 8080

jwt:
  secret: "a3f8d7e0b2c491a6f5289e3b762c8d4f1e9a6b5c4d3e2f1a0b9c8d7e6f5a4b3"
  expiration: 86400000  # Token 过期时间（24小时）
  tokenKeyPrefix: im:token

file:
  upload:
    maxSize: 5242880  # 最大文件大小（5MB）

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      # 连接池名称
      pool-name: IMHikariPool
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接池大小
      maximum-pool-size: 20
      # 连接超时时间(毫秒)
      connection-timeout: 30000
      # 连接最大存活时间(毫秒)
      max-lifetime: 1800000
      # 连接空闲超时时间(毫秒)
      idle-timeout: 600000
      # 连接测试查询
      connection-test-query: SELECT 1
      # 自动提交
      auto-commit: true
      # 其他数据源属性
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    host: localhost
    port: 6379
    password:  # 如果有密码，请设置
    database: 0
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数
        max-idle: 20    # 连接池中的最大空闲连接
        min-idle: 5     # 连接池中的最小空闲连接
        max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 500       # 连接超时时间（毫秒）
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
  global-config:
    db-config:
      id-type: auto # 主键自增
    banner: off

# 日志配置
logging:
  level:
    com.naz1k1: info
    org.springframework: warn

# RocketMQ配置
rocketmq:
  name-server: 43.138.171.240:9876  # RocketMQ NameServer地址
  producer:
    group: im-producer-group  # 生产者组名
    send-message-timeout: 3000  # 发送消息超时时间（毫秒）
    retry-times-when-send-failed: 2  # 发送失败重试次数
    retry-times-when-send-async-failed: 2  # 异步发送失败重试次数
  consumer:
    group: im-consumer-group  # 消费者组名
    pull-batch-size: 10  # 批量拉取消息数量

#netty:
#  port: 8090  # Netty服务器端口
#  host: 0.0.0.0  # Netty服务器主机地址